version: '3.8'

services:
  fastapi:
    image: amf0154/fastapi:1.5.4
    container_name: m2hydro-fastapi
    volumes:
      - /projects/shared/data:/project/data
      - /projects/shared/models:/project/stored_models
    ports:
      - "3100:3100"
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "api.main:app"]
