version: '3.8'

services:
  fastapi:
    image: amf0154/fastapi:1.3
    container_name: fastapi
    volumes:
      - /projects/shared:/code/shared
      - /projects/shared/data:/code/data
      - /projects/shared/models:/code/stored_models
    ports:
      - "3100:3100"
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "api.main:app"]
